language: java

os:
  - linux

dist: trusty

sudo: false

git:
  depth: 10   # don't need more than one level for our builds

cache:
  directories:
    - $HOME/.m2

before_install:
  - unset _JAVA_OPTIONS
  - rm ~/.m2/settings.xml

install:
  - pushd Propositional
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - popd

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk11

before_script:
  - unset _JAVA_OPTIONS # travis/travis#8408

script:
  - pushd Propositional
  - mvn -DskipTests=false test
  - popd

notifications:
  email: false